import "./globals.css";

export const metadata = {
  title: "World Holiday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="content-wrap">{children}</div>
        <footer>
          <span>
            Developed by
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://github.com/TingChiehLin/world-holidays"
            >
              Ting Chieh Lin
            </a>
          </span>
        </footer>
      </body>
    </html>
  );
}
