import "./globals.css";

export const metadata = {
  title: "World Holiday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="content-wrap">{children}</div>
        <footer>
          <span>Developer by Ting Chieh Lin</span>
        </footer>
      </body>
    </html>
  );
}
